services:
  postgres:
    image: postgres:13
    container_name: pruebas_dotnet
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - pruebas-dotnet-network

networks:
  pruebas-dotnet-network:
    driver: bridge